[package]
name = "musium_filesystem_sync"
version = "0.1.0"
authors = ["Gabriel Konat <gabrielkonat@gmail.com>"]
edition = "2018"
publish = false

[dependencies]
walkdir = "2"
id3 = "0.5"
crc32fast = "1"
thiserror = "1"
tracing = "0.1"
