[package]
name = "musium_audio"
version = "0.1.0"
authors = ["Gabriel Konat <gabrielkonat@gmail.com>"]
edition = "2018"
publish = false

[dependencies]
musium_core = {path = "../musium_core"}
rodio = "0.10"
thiserror = "1"
