cargo-features = ["named-profiles", "profile-overrides"]

[workspace]
members = [
  "code/core",
  "code/backend",
  "code/server",
  "code/client"
]

# Development/debugging profile:
[profile.dev]
opt-level = 0
overflow-checks = true
debug-assertions = true
panic = "abort"
debug = true
codegen-units = 8
lto = false
incremental = true

# Fast development profile: no debug information, more optimisations.
[profile.fastdev]
inherits = 'dev'
opt-level = 2
debug = false
# Fully optimize all dependencies, but not our own crates.
[profile.fastdev.package."*"]
opt-level = 3
[profile.fastdev.package."core"]
opt-level = 2
[profile.fastdev.package."backend"]
opt-level = 2
[profile.fastdev.package."server"]
opt-level = 2
[profile.fastdev.package."client"]
opt-level = 2

# Release (builtin) profile: fastest runtime.
[profile.release]
opt-level = 3
overflow-checks = false
debug-assertions = false
lto = true
debug = false
