cargo-features = ["named-profiles", "profile-overrides"]

[workspace]
members = [
  "code/core",
  "code/backend",
  "code/server",
  "code/client"
]

# Development (builtin & default) profile: debug assertions + fastest code generation.
[profile.dev]
opt-level = 2
overflow-checks = true
debug-assertions = true
panic = "abort"
debug = false
codegen-units = 8
lto = false
incremental = true
# Fully optimize all dependencies, but not our own crates.
[profile.dev.package."*"]
opt-level = 3
[profile.dev.package."core"]
opt-level = 2
[profile.dev.package."backend"]
opt-level = 2
[profile.dev.package."server"]
opt-level = 2
[profile.dev.package."client"]
opt-level = 2

# Release (builtin) profile: fastest runtime.
[profile.release]
opt-level = 3
overflow-checks = false
debug-assertions = false
lto = true
debug = false

# Debugging (custom) profile (cannot be called debug): dev + debugging symbols.
[profile.dbg]
inherits = 'dev'
debug = true
