[package]
name = "musium_audio_output_local"
version = "0.1.0"
authors = ["Gabriel Konat <gabrielkonat@gmail.com>"]
edition = "2018"
publish = false

[dependencies]
musium_core = { path = "../core" }
rodio = "0.13"
thiserror = "1"
