[package]
name = "musium_reqwest_util"
version = "0.1.0"
authors = ["Gabriel Konat <gabrielkonat@gmail.com>"]
edition = "2018"
publish = false

[dependencies]
musium_core = { path = "../musium_core" }
reqwest = { version = "0.10", features = ["json", "gzip"] }
url = "2"
serde = "1"
thiserror = "1"
