[package]
name = "core"
version = "0.1.0"
authors = ["Gabriel Konat <gabrielkonat@gmail.com>"]
edition = "2018"
publish = false

[dependencies]
diesel = { version = "1" }
serde = { version = "1", features = ["derive"] }
itertools = "0.8"
