[package]
name = "core"
version = "0.1.0"
authors = ["Gabriel Konat <gabrielkonat@gmail.com>"]
edition = "2018"
publish = false

[dependencies]
diesel = { version = "1.4", features = ["sqlite"] }
thiserror = "1.0"
metrics = "0.12"
tracing = "0.1"
